### ISSUE TITLE
Enzyme zero Kusama balance in folder

### ISSUE THREAD

**Issue by pieguy24** [blockxlabs/enzyme#10]
Before filing a new issue, please provide the following information.

## Basic Details
Enzyme version 0.5.2
Installed from Chrome Web Store

Chrome Version 83.0.4103.97
Windows 10.0.18363
MacOS 10.x.x/Windows 10.x/Ubuntu 18.x/etc

#### Which provider are you using?
Alexander/Custom (provide details)/Tested with multiple/Irrelevant to problem

## Problem Description
My Kusama Balance is displayed as zero. A few weeks ago I successfully setup and transferred, and subsequently saw the balance correctly depicted in my Enzyme wallet.. I just checked it today, after playing around with my cookies the other day and now I don't see the correct balance. I tried uninstalling Enzyme wallet and importing again but to no avail... Balance is still displayed as zero. Is there supposed to be a custom URL/network?

#### Code snippets/screenshots (if not in above questions)
![image](https://user-images.githubusercontent.com/66915736/84600663-0badb300-ae49-11ea-8219-24bed19e6820.png)

**Comment by zadmarbella** [comment]
@pieguy24 we are able to reproduce the issue and we are looking to resolve it. Thanks.

**Comment by zadmarbella** [comment]
@pieguy24  we have resolved the issue please verify thanks
https://chrome.google.com/webstore/detail/enzyme/amligljifngdnodkebecdijmhnhojohh

**Comment by pieguy24** [comment]
Greetings Ezadkiel,


Thank you so much for your assistance! The balance is restored! Can you
please tell me what happened, as I am also fearful that this may happen
again. Do you have any preventative suggestions in this regard or was this
just some sort of system maintenance?

Thanks again!

**Comment by zadmarbella** [comment]
@pieguy24 This was caused by updates that occurred with our dependencies and fall under system maintenance and upkeep. 

Thanks.
