### ISSUE TITLE
Can't send tokens

### ISSUE THREAD

**Issue by joeykrug** [blockxlabs/enzyme#11]
Before filing a new issue, please provide the following information.

#### Enzyme version
0.5.2

#### Installed from Chrome Web Store or Github release?
web store

#### Chrome version?
83.0

#### OS and version?
MacOS 10.x.x/Windows 10.x/Ubuntu 18.x/etc

Mac OS 10.15

#### Which provider are you using?
Alexander/Custom (provide details)/Tested with multiple/Irrelevant to problem

Irrelevant

#### Expected vs actual behaviour

I'd expect to be able to send tokens, but I can't.

#### Steps to reproduce

Try to send tokens within the extension itself, it just freezes when I attempt to. Or if I try to send them in the polkadot.js.org portal I get this error: ```signAndSend: error: Unable to send transaction.```

**Comment by joeykrug** [comment]
I also can't do anything else, like start delegating to a validator, etc.

**Comment by zadmarbella** [comment]
@joeykrug we have resolved the issue please verify thanks.
