### ISSUE TITLE
User should receive an insufficient balance warning while sending to an address selected from the address book.

### ISSUE THREAD

**Issue by ChinmayPatel** [blockxlabs/enzyme#12]
# Steps to Reproduce
Install Enzyme's latest version.
Create a standard account.
Create an address book entry.
Click on the `Send` button from the wallet dashboard. It should show a `Send` page.
In the `To` field select an account from the address book.
In the `Amount` field, enter 100 KSMs (some large number than your current balance).
Press `Next` button. 

It should show an error for the insufficient balance, but instead it shows a blank page after the loading symbol.

**Comment by zadmarbella** [comment]
we have resolved this issue on version 0.5.4
https://addons.mozilla.org/en-CA/firefox/addon/enzyme/versions/
