### ISSUE TITLE
Transaction pill sometimes showing pending and never goes to success.

### ISSUE THREAD

**Issue by kuntesh87** [blockxlabs/enzyme#5]
Before filing a new issue, please provide the following information.

#### Enzyme version
0.4.4

#### Installed from Chrome Web Store or Github release?
web store

#### Chrome version?
75.0.3770.100 (Official Build) (64-bit)

#### OS and version?
Windows 10

#### Which provider are you using?
Alexander

#### Steps to reproduce

1)Send some dot to any valid address using enzyme.
2)Dashboard Transaction list update with new pending Transaction.
3) Pending will not change to Sucess but my balance was updated.

**Comment by kushptlapigarage** [comment]
Sent few txns over last few days, all turns success. I have a hunch that it's related to Polkadot block produce speed and connectivity both.
