### ISSUE TITLE
user is seeing issues on balances of 150milli or less

### ISSUE THREAD

**Issue by zadmarbella** [blockxlabs/enzyme#9]
Before filing a new issue, please provide the following information.

#### Enzyme version
0.5.1

#### Installed from Chrome Web Store or Github release?
Chrome Web Store

#### Chrome version?
83.0.4103.61

#### OS and version?
MacOS 10.x.x

#### Which provider are you using?
Kusama

#### Expected vs actual behaviour
user is seeing issues on balances of 150milli KSM or less.

**Comment by kushptlapigarage** [comment]
@zadmarbella do we still need this issue open ?

**Comment by zadmarbella** [comment]
fixed now thanks
